---
# ref: https://github.com/dbcli/awscli/blob/v1.8.1/README.md#quick-start

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  become: yes

- name: Install python-pip via apt.
  apt: "name=python-pip state=installed"
  become: yes
